if(NOT DEFINED INPUT_FILE OR NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "GenerateOpenDRTCLSource.cmake requires INPUT_FILE and OUTPUT_FILE")
endif()

file(READ "${INPUT_FILE}" OPENCL_SOURCE_CONTENT)

# Note-to-self:
# Emit split escaped string literals to avoid MSVC "string too big" limits
# while preserving exact kernel source text.
string(REPLACE "\\" "\\\\" OPENCL_SOURCE_ESCAPED "${OPENCL_SOURCE_CONTENT}")
string(REPLACE "\"" "\\\"" OPENCL_SOURCE_ESCAPED "${OPENCL_SOURCE_ESCAPED}")
string(REPLACE "\r\n" "\n" OPENCL_SOURCE_ESCAPED "${OPENCL_SOURCE_ESCAPED}")
string(REPLACE "\r" "\n" OPENCL_SOURCE_ESCAPED "${OPENCL_SOURCE_ESCAPED}")
string(REPLACE "\n" "\\n\"\n\"" OPENCL_SOURCE_ESCAPED "${OPENCL_SOURCE_ESCAPED}")

set(HEADER_TEXT
"#pragma once

#include <cstddef>

// Generated from src/opencl/OpenDRT.cl
// Do not edit this file directly.
static constexpr const char kOpenDRTCLSource[] =
\"${OPENCL_SOURCE_ESCAPED}\";

static constexpr std::size_t kOpenDRTCLSourceSize = sizeof(kOpenDRTCLSource) - 1;
")

file(WRITE "${OUTPUT_FILE}" "${HEADER_TEXT}")
